/**
 * @file InputCapture9.c
 * @author Seb Madgwick
 * @brief Input capture driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "InputCapture9.h"
#include "Timer/Timer.h"

//------------------------------------------------------------------------------
// Variables

const InputCapture inputCapture9 = {
    .initialise = InputCapture9Initialise,
    .deinitialise = InputCapture9Deinitialise,
    .bufferOverrun = InputCapture9BufferOverrun,
};

static void (*captureEvent)(const uint64_t ticks);

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param settings Settings.
 * @param captureEvent_ Capture event callback.
 */
void InputCapture9Initialise(const InputCaptureSettings * const settings, void (*const captureEvent_) (const uint64_t ticks)) {

    // Ensure default register states
    InputCapture9Deinitialise();

    // Configure input capture
    switch (settings->edge) {
        case InputCaptureEdgeFalling:
            IC9CONbits.ICM = 0b010; // simple Capture Event mode - every falling edge
            break;
        case InputCaptureEdgeRising:
            IC9CONbits.ICM = 0b011; // simple Capture Event mode - every rising edge
            break;
        case InputCaptureEdgeEvery:
            IC9CONbits.ICM = 0b110; // simple Capture Event mode ? every edge, specified edge first and every edge thereafter
            break;
    }
    switch (settings->interrupt) {
        case InputCaptureInterruptEvery:
            IC9CONbits.ICI = 0b00; // interrupt on every capture event
            break;
        case InputCaptureInterruptSecond:
            IC9CONbits.ICI = 0b01; // interrupt on every second capture event
            break;
        case InputCaptureInterruptThird:
            IC9CONbits.ICI = 0b10; // interrupt on every third capture event
            break;
        case InputCaptureInterruptFourth:
            IC9CONbits.ICI = 0b11; // interrupt on every forth capture event
            break;
    }
    IC9CONbits.C32 = 1;

    // Enable interrupt
    captureEvent = captureEvent_;
    EVIC_SourceEnable(INT_SOURCE_INPUT_CAPTURE_9);

    // Enable
    IC9CONbits.ON = 1;
}

/**
 * @brief Deinitialises the module.
 */
void InputCapture9Deinitialise(void) {
    IC9CON = 0;
    EVIC_SourceDisable(INT_SOURCE_INPUT_CAPTURE_9);
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_9);
}

/**
 * @brief Triggers a capture event.
 */
void InputCapture9Trigger(void) {
    EVIC_SourceStatusSet(INT_SOURCE_INPUT_CAPTURE_9);
}

/**
 * @brief Returns true if the hardware receive buffer has overrun.
 * @return True if the hardware receive buffer has overrun.
 */
bool InputCapture9BufferOverrun(void) {
    return IC9CONbits.ICOV;
}

/**
 * @brief External interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void InputCapture9InterruptHandler(void) {
    const uint64_t now = TimerGetTicks64();
    while (IC9CONbits.ICBNE) {
        const uint32_t latency = (uint32_t) now - (uint32_t) IC9BUF;
        captureEvent(now - (uint64_t) latency);
    }
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_9);
}

//------------------------------------------------------------------------------
// End of file
