/**
 * @file InputCapture1.c
 * @author Seb Madgwick
 * @brief Input capture driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "InputCapture1.h"
#include "Timer/Timer.h"

//------------------------------------------------------------------------------
// Variables

static void (*captureEvent)(const uint64_t ticks);

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param edge Edge.
 * @param captureEvent_ Capture event callback.
 */
void InputCapture1Initialise(const InputCaptureEdge edge, void (*const captureEvent_) (const uint64_t ticks)) {

    // Ensure default register states
    InputCapture1Deinitialise();

    // Configure input capture
    switch (edge) {
        case InputCaptureEdgeFalling:
            IC1CONbits.ICM = 0b010; // simple Capture Event mode - every falling edge
            break;
        case InputCaptureEdgeRising:
            IC1CONbits.ICM = 0b011; // simple Capture Event mode - every rising edge
            break;
    }
    IC1CONbits.C32 = 1;

    // Enable interrupt
    captureEvent = captureEvent_;
    EVIC_SourceEnable(INT_SOURCE_INPUT_CAPTURE_1);

    // Enable
    IC1CONbits.ON = 1;
}

/**
 * @brief Deinitialises the module.
 */
void InputCapture1Deinitialise(void) {
    IC1CON = 0;
    EVIC_SourceDisable(INT_SOURCE_INPUT_CAPTURE_1);
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_1);
}

/**
 * @brief Triggers a capture event.
 */
void InputCapture1Trigger(void) {
    EVIC_SourceStatusSet(INT_SOURCE_INPUT_CAPTURE_1);
}

/**
 * @brief External interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void InputCapture1InterruptHandler(void) {
    const uint64_t now = TimerGetTicks64();
    while (IC1CONbits.ICBNE) {
        const uint32_t latency = (uint32_t) now - (uint32_t) IC1BUF;
        captureEvent(now - (uint64_t) latency);
    }
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_1);
}

//------------------------------------------------------------------------------
// End of file
