/**
 * @file InputCapture1.c
 * @author Seb Madgwick
 * @brief Input capture driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "InputCapture1.h"
#include "Timer/Timer.h"

//------------------------------------------------------------------------------
// Variables

const InputCapture inputCapture1 = {
    .initialise = InputCapture1Initialise,
    .deinitialise = InputCapture1Deinitialise,
    .bufferOverrun = InputCapture1BufferOverrun,
};

static void (*captureEvent)(const uint64_t ticks);

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param settings Settings.
 * @param captureEvent_ Capture event callback.
 */
void InputCapture1Initialise(const InputCaptureSettings * const settings, void (*const captureEvent_) (const uint64_t ticks)) {

    // Ensure default register states
    InputCapture1Deinitialise();

    // Configure input capture
    switch (settings->edge) {
        case InputCaptureEdgeFalling:
            IC1CONbits.ICM = 0b010; // simple Capture Event mode - every falling edge
            break;
        case InputCaptureEdgeRising:
            IC1CONbits.ICM = 0b011; // simple Capture Event mode - every rising edge
            break;
        case InputCaptureEdgeEvery:
            IC1CONbits.ICM = 0b110; // simple Capture Event mode - every edge, specified edge first and every edge thereafter
            break;
    }
    switch (settings->interrupt) {
        case InputCaptureInterruptEvery:
            IC1CONbits.ICI = 0b00; // interrupt on every capture event
            break;
        case InputCaptureInterruptSecond:
            IC1CONbits.ICI = 0b01; // interrupt on every second capture event
            break;
        case InputCaptureInterruptThird:
            IC1CONbits.ICI = 0b10; // interrupt on every third capture event
            break;
        case InputCaptureInterruptFourth:
            IC1CONbits.ICI = 0b11; // interrupt on every forth capture event
            break;
    }
    IC1CONbits.FEDGE = settings->firstEdge ? 1 : 0;
    IC1CONbits.C32 = 1;

    // Enable interrupt
    captureEvent = captureEvent_;
    EVIC_SourceEnable(INT_SOURCE_INPUT_CAPTURE_1);

    // Enable
    IC1CONbits.ON = 1;
}

/**
 * @brief Deinitialises the module.
 */
void InputCapture1Deinitialise(void) {
    IC1CON = 0;
    EVIC_SourceDisable(INT_SOURCE_INPUT_CAPTURE_1);
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_1);
}

/**
 * @brief Triggers a capture event.
 */
void InputCapture1Trigger(void) {
    EVIC_SourceStatusSet(INT_SOURCE_INPUT_CAPTURE_1);
}

/**
 * @brief Returns true if the hardware receive buffer has overrun.
 * @return True if the hardware receive buffer has overrun.
 */
bool InputCapture1BufferOverrun(void) {
    return IC1CONbits.ICOV;
}

/**
 * @brief External interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void InputCapture1InterruptHandler(void) {
    while (IC1CONbits.ICBNE) {
        const uint64_t now = TimerGetTicks64();
        const uint32_t latency = (uint32_t) now - (uint32_t) IC1BUF;
        captureEvent(now - (uint64_t) latency);
    }
    EVIC_SourceStatusClear(INT_SOURCE_INPUT_CAPTURE_1);
}

//------------------------------------------------------------------------------
// End of file
