/**
 * @file I2C3.c
 * @author Seb Madgwick
 * @brief I2C driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "I2C3.h"
#include <stddef.h>
#include "Timer/Timer.h"

//------------------------------------------------------------------------------
// Function declarations

static void WaitForInterruptOrTimeout(void);

//------------------------------------------------------------------------------
// Variables

static I2CMessage* message;
static uint64_t timeout;

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param clockFrequency Clock frequency.
 */
void I2C3Initialise(const I2CClockFrequency clockFrequency) {

    // Ensure default register states
    I2C3Deinitialise();

    // Configure I2C
    I2C3BRG = I2CCalculateI2Cxbrg(clockFrequency);
    if (clockFrequency != I2CClockFrequency400kHz) {
        I2C3CONbits.DISSLW = 1; // Slew rate control disabled
    }
    I2C3CONbits.I2CEN = 1;
}

/**
 * @brief Disable the module.
 */
void I2C3Deinitialise(void) {

    // Disable I2C and restore default register states
    I2C3CON = 0;
    I2C3STAT = 0;

    // Disable interrupt
    EVIC_SourceDisable(INT_SOURCE_I2C3_MASTER);
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
}

/**
 * @brief Generates a start event.
 */
void I2C3Start(void) {
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3CONbits.SEN = 1;
    WaitForInterruptOrTimeout();
}

/**
 * @brief Generates a repeated start event.
 */
void I2C3RepeatedStart(void) {
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3CONbits.RSEN = 1;
    WaitForInterruptOrTimeout();
}

/**
 * @brief Generates a stop event.
 */
void I2C3Stop(void) {
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3CONbits.PEN = 1;
    WaitForInterruptOrTimeout();
}

/**
 * @brief Sends a byte and checks for ACK.
 * @param byte Byte.
 * @return True if an ACK was generated.
 */
bool I2C3Send(const uint8_t byte) {
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3STATbits.ACKSTAT = 0;
    I2C3TRN = byte;
    WaitForInterruptOrTimeout();
    return I2C3STATbits.ACKSTAT == 0;
}

/**
 * @brief Receives a byte and generates an ACK or NACK.
 * @param ack True for ACK.
 * @return Byte.
 */
uint8_t I2C3Receive(const bool ack) {

    // Receive
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3CONbits.RCEN = 1;
    WaitForInterruptOrTimeout();

    // ACK/NACK
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER);
    I2C3CONbits.ACKDT = ack ? 0 : 1;
    I2C3CONbits.ACKEN = 1;
    WaitForInterruptOrTimeout();
    return I2C3RCV;
}

/**
 * @brief Waits for the interrupt or timeout.
 */
static void WaitForInterruptOrTimeout(void) {
    const uint64_t timeout = TimerGetTicks64() + (TIMER_TICKS_PER_SECOND / (I2CClockFrequency100kHz / 10)); // 10 clock cycles timeout for slowest clock
    while (true) {
        if (EVIC_SourceStatusGet(INT_SOURCE_I2C3_MASTER)) {
            break;
        }
        if (TimerGetTicks64() > timeout) {
            break;
        }
    }
}

/**
 * @brief Begins message.
 * @param message Message.
 */
void I2C3BeginMessage(I2CMessage * const message_) {

    // Do nothing if message in progress
    if (I2C3MessageInProgress()) {
        return;
    }

    // Set message
    message = message_;
    message_->index = 0;

    // Calculate message timeout
    timeout = TimerGetTicks64() + (I2C_MESSAGE_MAX_LENGTH * I2C_TIMEOUT);

    // Trigger first interrupt
    EVIC_SourceStatusSet(INT_SOURCE_I2C3_MASTER);
    EVIC_SourceEnable(INT_SOURCE_I2C3_MASTER);
}

/**
 * @brief Returns true if the message is in progress.
 * @return True if the message is in progress.
 */
bool I2C3MessageInProgress(void) {
    if (TimerGetTicks64() >= timeout) {
        EVIC_SourceDisable(INT_SOURCE_I2C3_MASTER);
    }
    return EVIC_SourceIsEnabled(INT_SOURCE_I2C3_MASTER);
}

/**
 * @brief I2C interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void I2C3InterruptHandler(void) {
    EVIC_SourceStatusClear(INT_SOURCE_I2C3_MASTER); // clear interrupt flag first because next event may complete before ISR returns
    const int index = message->index++;
    switch (message->event[index]) {
        case I2CMessageEventStart:
            I2C3CONbits.SEN = 1;
            break;
        case I2CMessageEventRepeatedStart:
            I2C3CONbits.RSEN = 1;
            break;
        case I2CMessageEventStop:
            I2C3CONbits.PEN = 1;
            break;
        case I2CMessageEventSend:
            I2C3TRN = message->data[index];
            break;
        case I2CMessageEventReceive:
            I2C3CONbits.RCEN = 1;
            break;
        case I2CMessageEventAck:
            *message->destination[index] = I2C3RCV;
            I2C3CONbits.ACKDT = 0;
            I2C3CONbits.ACKEN = 1;
            break;
        case I2CMessageEventNack:
            *message->destination[index] = I2C3RCV;
            I2C3CONbits.ACKDT = 1;
            I2C3CONbits.ACKEN = 1;
            break;
        case I2CMessageEventEnd:
            EVIC_SourceDisable(INT_SOURCE_I2C3_MASTER);
            if (message->complete != NULL) {
                message->complete();
            }
            break;
    }
}

//------------------------------------------------------------------------------
// End of file
