from itertools import chain, dropwhile, takewhile
from pathlib import Path


def insert(path: Path, id: int, block: str):
    lines = path.read_text().splitlines(keepends=True)

    start_key = f"// Start of code block #{id} generated by {Path(__file__).name}\n"
    end_key = f"// End of code block #{id} generated by {Path(__file__).name}\n"

    lines_before_block = list(
        chain(
            takewhile(lambda l: not l.lstrip().startswith(start_key), lines),
            [next(line for line in lines if line.lstrip().startswith(start_key))],
        )
    )

    lines_after_block = list(dropwhile(lambda l: not l.lstrip().startswith(end_key), lines))

    if lines_before_block == lines:
        raise Exception(f"Error: Cannot find {start_key.strip()} in {path}")

    if lines_after_block == lines:
        raise Exception(f"Error: Cannot find {end_key.strip()} in {path}")

    path.write_text("".join(lines_before_block) + block + "".join(lines_after_block))


# Get enum values
path = Path("../../config/default/peripheral/rcon/plib_rcon.h")

if not path.exists():
    raise Exception("Please enable RCON in MPLAB Harmony")

PREFIX = "RCON_RESET_CAUSE_"

enums = [PREFIX + l.split(PREFIX)[1].split(" ")[0] for l in path.read_text().splitlines() if PREFIX in l]

# Insert code in ResetCauseGet()
path = Path("ResetCause.c")

insert(
    path,
    0,
    "    const RCON_RESET_CAUSE mask = " + " | ".join(enums) + ";\n",
)

insert(
    path,
    1,
    "".join(
        f"""\
    if ((cause & {e}) != 0) {{
        printf("{e.replace(PREFIX, "")} ");
    }}\n"""
        for e in enums
    ),
)
