import os


def insert(file_path, code, id):
    with open(file_path) as file:
        all_lines = file.readlines()

    start_key = f"// Start of code block #{id} generated by {os.path.basename(__file__)}\n"
    end_key = f"// End of code block #{id} generated by {os.path.basename(__file__)}\n"

    waiting_for_start = True
    waiting_for_end = True
    lines_before_start = []
    lines_after_end = []

    for line in all_lines:
        if waiting_for_start:
            lines_before_start += line

            if line.strip() == start_key.strip():
                waiting_for_start = False

            continue

        if waiting_for_end:
            if line.strip() == end_key.strip():
                lines_after_end += line
                waiting_for_end = False

            continue
        else:
            lines_after_end += line

    if waiting_for_start:
        raise Exception(f"Error: Cannot find {start_key.strip()} in {file_path}")

    if waiting_for_end:
        raise Exception(f"Error: Cannot find {end_key.strip()} in {file_path}")

    with open(file_path, "w") as file:
        for line in lines_before_start:
            file.write(line)

        file.write(code)

        for line in lines_after_end:
            file.write(line)


# Get enum values
file_path = "../../config/default/peripheral/rcon/plib_rcon.h"

if not os.path.exists(file_path):
    raise Exception("Please enable RCON in MPLAB Harmony")

with open(file_path) as file:
    lines = file.readlines()

enum_values = []

for line in lines:
    prefix = "RCON_RESET_CAUSE_"

    if prefix in line:
        enum_values.append(prefix + line.split(prefix)[1].split(" ")[0])

# Insert code in ResetCauseGet()
file_path = "ResetCause.c"

code = "    const RCON_RESET_CAUSE mask = "

for enum_value in enum_values:
    code += enum_value + " | "

code = code[0 : -len(" | ")]
code += ";\n"

insert(file_path, code, "0")

# Insert code in ResetCausePrint()
code = ""

for enum_value in enum_values:
    code += "    if ((cause & " + enum_value + ") != 0) {\n"
    code += '        printf("' + enum_value.replace("RCON_RESET_CAUSE_", "") + ' ");\n'
    code += "    }\n"

insert(file_path, code, "1")
