/**
 * @file ResetCause.c
 * @author Seb Madgwick
 * @brief Indicates the cause of a device reset.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "ResetCause.h"
#include <stdbool.h>
#include <stdio.h> // printf

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Gets the reset cause.  This function can only be called once.
 * @return Reset cause.
 */
RCON_RESET_CAUSE ResetCauseGet() {
    // Start of code block #0 generated by generate_reset_cause.py
    const RCON_RESET_CAUSE mask = RCON_RESET_CAUSE_POR | RCON_RESET_CAUSE_BOR | RCON_RESET_CAUSE_IDLE | RCON_RESET_CAUSE_SLEEP | RCON_RESET_CAUSE_WDTO | RCON_RESET_CAUSE_DMTO | RCON_RESET_CAUSE_SWR | RCON_RESET_CAUSE_EXTR | RCON_RESET_CAUSE_CMR | RCON_RESET_CAUSE_BCFGFAIL | RCON_RESET_CAUSE_BCFGERR;
    // End of code block #0 generated by generate_reset_cause.py
    const RCON_RESET_CAUSE cause = RCON_ResetCauseGet() & mask;
    RCON_ResetCauseClear(mask);
    return cause;
}

/**
 * @brief Prints the reset cause.
 * @return Reset cause.
 */
void ResetCausePrint(const RCON_RESET_CAUSE cause) {
    printf("Reset ");
    // Start of code block #1 generated by generate_reset_cause.py
    if ((cause & RCON_RESET_CAUSE_POR) != 0) {
        printf("POR ");
    }
    if ((cause & RCON_RESET_CAUSE_BOR) != 0) {
        printf("BOR ");
    }
    if ((cause & RCON_RESET_CAUSE_IDLE) != 0) {
        printf("IDLE ");
    }
    if ((cause & RCON_RESET_CAUSE_SLEEP) != 0) {
        printf("SLEEP ");
    }
    if ((cause & RCON_RESET_CAUSE_WDTO) != 0) {
        printf("WDTO ");
    }
    if ((cause & RCON_RESET_CAUSE_DMTO) != 0) {
        printf("DMTO ");
    }
    if ((cause & RCON_RESET_CAUSE_SWR) != 0) {
        printf("SWR ");
    }
    if ((cause & RCON_RESET_CAUSE_EXTR) != 0) {
        printf("EXTR ");
    }
    if ((cause & RCON_RESET_CAUSE_CMR) != 0) {
        printf("CMR ");
    }
    if ((cause & RCON_RESET_CAUSE_BCFGFAIL) != 0) {
        printf("BCFGFAIL ");
    }
    if ((cause & RCON_RESET_CAUSE_BCFGERR) != 0) {
        printf("BCFGERR ");
    }
    // End of code block #1 generated by generate_reset_cause.py
    printf("\r\n");
}

//------------------------------------------------------------------------------
// End of file
