/**
 * @file Spi1.c
 * @author Seb Madgwick
 * @brief SPI driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "Spi1.h"

//------------------------------------------------------------------------------
// Definitions

/**
 * @brief Uncomment this line to enable printing of transfers.
 */
//#define PRINT_TRANSFERS

//------------------------------------------------------------------------------
// Variables

static GPIO_PIN csPin;
static uint8_t* data;
static size_t numberOfBytes;
static void (*transferComplete)(void);
static size_t readIndex;

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param settings Settings.
 */
void Spi1Initialise(const SpiSettings * const settings) {

    // Ensure default register states
    Spi1Deinitialise();

    // Configure SPI
    SPI1CONbits.MSTEN = 1; // host mode
    SPI1CONbits.ENHBUF = 1; // enhanced Buffer mode is enabled
    SPI1CONbits.SMP = 1; // input data sampled at end of data output time
    SPI1CONbits.CKP = settings->clockPolarity;
    SPI1CONbits.CKE = settings->clockPhase;
    SPI1CONbits.STXISEL = 0b11; // interrupt is generated when the buffer is not full (has one or more empty elements)
    SPI1CONbits.SRXISEL = 0b01; // interrupt is generated when the buffer is not empty
    SPI1BRG = SpiCalculateSpixbrg(settings->clockFrequency);
    SPI1CONbits.ON = 1;

    // Enable interrupts
    EVIC_SourceEnable(INT_SOURCE_SPI1_RX);
}

/**
 * @brief Deinitialises the module.
 */
void Spi1Deinitialise(void) {

    // Disable SPI and restore default register states
    SPI1CON = 0;
    SPI1CON2 = 0;
    SPI1STAT = 0;
    SPI1BRG = 0;

    // Disable interrupt
    EVIC_SourceDisable(INT_SOURCE_SPI1_RX);
    EVIC_SourceStatusClear(INT_SOURCE_SPI1_RX);
}

/**
 * @brief Transfers data. The data will be overwritten with the received data.
 * This function must not be called while a transfer is in progress. The
 * transfer complete callback will be called from within an interrupt once the
 * transfer is complete.
 * @param csPin_ CS pin.
 * @param data_ Data.
 * @param numberOfBytes_ Number of bytes.
 * @param transferComplete_ Transfer complete callback.
 */
void Spi1Transfer(const GPIO_PIN csPin_, void* const data_, const size_t numberOfBytes_, void (*transferComplete_)(void)) {

    // Store arguments
    csPin = csPin_;
    data = data_;
    numberOfBytes = numberOfBytes_;
    transferComplete = transferComplete_;
    readIndex = 0;

    // Print
#ifdef PRINT_TRANSFERS
    SpiPrintTransfer(csPin, data, numberOfBytes);
#endif

    // Begin transfer
    if (csPin != GPIO_PIN_NONE) {
        GPIO_PinClear(csPin);
    }
    for (size_t index = 0; index < numberOfBytes; index++) {
        while (SPI1STATbits.SPITBF == 1); // wait while no available space in the FIFO
        SPI1BUF = data[index];
    }
}

/**
 * @brief SPI RX interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void Spi1RXInterruptHandler(void) {

    // Read data
    while (SPI1STATbits.SPIRBE == 0) { // while RX FIFO is not empty
        data[readIndex++] = SPI1BUF;
    }
    EVIC_SourceStatusClear(INT_SOURCE_SPI1_RX); // clear interrupt flag first because transfer complete callback may start new transfer
    if (readIndex < numberOfBytes) {
        return;
    }

    // End transfer
    if (csPin != GPIO_PIN_NONE) {
        GPIO_PinSet(csPin);
    }
#ifdef PRINT_TRANSFERS
    SpiPrintTransferComplete(data, numberOfBytes);
#endif
    if (transferComplete != NULL) {
        transferComplete();
    }
}

/**
 * @brief Returns true while the transfer is in progress.
 * @return True while the transfer is in progress.
 */
bool Spi1TransferInProgress(void) {
    return readIndex < numberOfBytes;
}

//------------------------------------------------------------------------------
// End of file
