/**
 * @file Spi5Dma.c
 * @author Seb Madgwick
 * @brief SPI driver using DMA for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "definitions.h"
#include "Spi5Dma.h"
#include "sys/kmem.h"

//------------------------------------------------------------------------------
// Variables

static void (*transferComplete)();

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param settings Settings.
 */
void Spi5DmaInitialise(const SpiSettings * const settings) {

    // Ensure default register states
    Spi5DmaDisable();

    // Configure SPI
    SPI5CONbits.MSTEN = 1; // Master mode
    SPI5CONbits.SMP = 1; // Input data sampled at end of data output time
    SPI5CONbits.CKP = settings->clockPolarity;
    SPI5CONbits.CKE = settings->clockPhase;
    SPI5BRG = SpiCalculateSpixbrg(settings->clockFrequency);
    SPI5CONbits.ON = 1;

    // Enable DMA
    DMACONbits.ON = 1;

    // Configure TX DMA channel
#ifdef _SPI5_TX_IRQ
    DCH0ECONbits.CHSIRQ = _SPI5_TX_IRQ;
#else
    DCH0ECONbits.CHSIRQ = _SPI5_TX_VECTOR;
#endif
    DCH0ECONbits.SIRQEN = 1; // Start channel cell transfer if an interrupt matching CHSIRQ occurs
    DCH0DSA = KVA_TO_PA(&SPI5BUF); // destination address
    DCH0DSIZ = 1; // destination size
    DCH0CSIZ = 1; // transfers per event

    // Configure RX DMA channel
#ifdef _SPI5_RX_IRQ
    DCH1ECONbits.CHSIRQ = _SPI5_RX_IRQ;
#else
    DCH1ECONbits.CHSIRQ = _SPI5_RX_VECTOR;
#endif
    DCH1ECONbits.SIRQEN = 1; // Start channel cell transfer if an interrupt matching CHSIRQ occurs
    DCH1SSA = KVA_TO_PA(&SPI5BUF); // source address
    DCH1SSIZ = 1; // source size
    DCH1CSIZ = 1; // transfers per event
    DCH1INTbits.CHBCIE = 1; // Channel Block Transfer Complete Interrupt Enable bit

    // Configure RX DMA channel interrupt
    EVIC_SourceStatusClear(INT_SOURCE_DMA1);
    EVIC_SourceEnable(INT_SOURCE_DMA1);
}

/**
 * @brief Disables the module.
 */
void Spi5DmaDisable() {

    // Disable SPI and restore default register states
    SPI5CON = 0;
    SPI5CON2 = 0;
    SPI5STAT = 0;
    SPI5BRG = 0;

    // Disable TX DMA channel and restore default register states
    DCH0CON = 0;
    DCH0ECON = 0;
    DCH0INT = 0;
    DCH0SSA = 0;
    DCH0DSA = 0;
    DCH0SSIZ = 0;
    DCH0DSIZ = 0;
    DCH0SPTR = 0;
    DCH0DPTR = 0;
    DCH0CSIZ = 0;
    DCH0CPTR = 0;
    DCH0DAT = 0;

    // Disable RX DMA channel and restore default register states
    DCH1CON = 0;
    DCH1ECON = 0;
    DCH1INT = 0;
    DCH1SSA = 0;
    DCH1DSA = 0;
    DCH1SSIZ = 0;
    DCH1DSIZ = 0;
    DCH1SPTR = 0;
    DCH1DPTR = 0;
    DCH1CSIZ = 0;
    DCH1CPTR = 0;
    DCH1DAT = 0;

    // Disable interrupt
    EVIC_SourceDisable(INT_SOURCE_DMA1);
    EVIC_SourceStatusClear(INT_SOURCE_DMA1);
}

/**
 * @brief Sets the transfer complete callback function.  This callback function
 * will be called from within an interrupt once the transfer is complete.
 * @param transferComplete Transfer complete callback function.
 */
void Spi5DmaSetTransferCompleteCallback(void (*transferComplete_)()) {
    EVIC_SourceDisable(INT_SOURCE_DMA1);
    transferComplete = transferComplete_;
    EVIC_SourceEnable(INT_SOURCE_DMA1);
}

/**
 * @brief Transfers data.  The data being transmitted will be overwritten with
 * the received data.  The data must be declared __attribute__((coherent)) for
 * PIC32MZ devices.  This function must not be called while a transfer is in
 * progress.
 * @param data Data.
 * @param numberOfBytes Number of bytes.
 */
void Spi5DmaTransfer(void* const data, const size_t numberOfBytes) {

    // Configure TX DMA channel
    DCH0SSA = KVA_TO_PA(data); // source address
    DCH0SSIZ = numberOfBytes; // source size

    // Configure RX DMA channel
    DCH1DSA = KVA_TO_PA(data); // destination address
    DCH1DSIZ = numberOfBytes; // destination size

    // Begin transfer
    DCH1INTbits.CHBCIF = 0; // clear RX DMA channel interrupt flag
    DCH1CONbits.CHEN = 1; // enable RX DMA channel
    DCH0CONbits.CHEN = 1; // enable TX DMA channel to begin transfer
}

/**
 * @brief DMA interrupt handler.  This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void Dma1InterruptHandler() {
    EVIC_SourceStatusClear(INT_SOURCE_DMA1); // clear interrupt flag first because callback function may start new transfer
    if (transferComplete != NULL) {
        transferComplete();
    }
}

/**
 * @brief Returns true while the transfer is in progress.
 * @return True while the transfer is in progress.
 */
bool Spi5DmaIsTransferInProgress() {
    return (DCH1CONbits.CHEN == 1); // if RX DMA channel interrupt enabled
}

//------------------------------------------------------------------------------
// End of file
