/**
 * @file Spi6.c
 * @author Seb Madgwick
 * @brief SPI driver for PIC32 devices.
 */

//------------------------------------------------------------------------------
// Includes

#include "Config.h"
#include "definitions.h"
#include "Spi6.h"

//------------------------------------------------------------------------------
// Definitions

/**
 * @brief Uncomment this line to print transfers.
 */
//#define PRINT_TRANSFERS

//------------------------------------------------------------------------------
// Variables

const Spi spi6 = {
    .transfer = Spi6Transfer,
    .transferInProgress = Spi6TransferInProgress,
};
static GPIO_PIN csPin;
static uint8_t* data;
static size_t numberOfBytes;
static void (*transferComplete)(void);
static size_t readIndex;

//------------------------------------------------------------------------------
// Functions

/**
 * @brief Initialises the module.
 * @param settings Settings.
 */
void Spi6Initialise(const SpiSettings * const settings) {

    // Ensure default register states
    Spi6Deinitialise();

    // Configure SPI
    SPI6CONbits.MSTEN = 1; // host mode
    SPI6CONbits.ENHBUF = 1; // enhanced Buffer mode is enabled
    SPI6CONbits.SMP = 1; // input data sampled at end of data output time
    SPI6CONbits.CKP = settings->clockPolarity;
    SPI6CONbits.CKE = settings->clockPhase;
    SPI6CONbits.STXISEL = 0b11; // interrupt is generated when the buffer is not full (has one or more empty elements)
    SPI6CONbits.SRXISEL = 0b01; // interrupt is generated when the buffer is not empty
    SPI6BRG = SpiCalculateSpixbrg(settings->clockFrequency);
    SPI6CONbits.ON = 1;

    // Enable interrupts
    EVIC_SourceEnable(INT_SOURCE_SPI6_RX);
}

/**
 * @brief Deinitialises the module.
 */
void Spi6Deinitialise(void) {

    // Disable SPI and restore default register states
    SPI6CON = 0;
    SPI6CON2 = 0;
    SPI6STAT = 0;
    SPI6BRG = 0;

    // Disable interrupt
    EVIC_SourceDisable(INT_SOURCE_SPI6_RX);
    EVIC_SourceStatusClear(INT_SOURCE_SPI6_RX);
}

/**
 * @brief Transfers data. The data will be overwritten with the received data.
 * This function will block if the number of bytes is greater than the 16 bytes.
 * This function must not be called while a transfer is in progress. The
 * transfer complete callback will be called from within an interrupt once the
 * transfer is complete.
 * @param csPin_ CS pin.
 * @param data_ Data.
 * @param numberOfBytes_ Number of bytes.
 * @param transferComplete_ Transfer complete callback.
 */
void Spi6Transfer(const GPIO_PIN csPin_, volatile void* const data_, const size_t numberOfBytes_, void (*const transferComplete_) (void)) {

    // Store arguments
    csPin = csPin_;
    data = (uint8_t*) data_;
    numberOfBytes = numberOfBytes_;
    transferComplete = transferComplete_;
    readIndex = 0;

    // Print
#ifdef PRINT_TRANSFERS
    SpiPrintTransfer(csPin, data, numberOfBytes);
#endif

    // Begin transfer
    if (csPin != GPIO_PIN_NONE) {
#ifdef SPI6_CS_ACTIVE_HIGH
        GPIO_PinSet(csPin);
#else
        GPIO_PinClear(csPin);
#endif
    }
    for (size_t index = 0; index < numberOfBytes; index++) {
        while (SPI6STATbits.SPITBF == 1); // wait while no space available in the FIFO
        SPI6BUF = data[index];
    }
}

/**
 * @brief SPI RX interrupt handler. This function should be called by the ISR
 * implementation generated by MPLAB Harmony.
 */
void Spi6RXInterruptHandler(void) {

    // Read data
    while (SPI6STATbits.SPIRBE == 0) { // while RX FIFO is not empty
        data[readIndex++] = SPI6BUF;
    }
    EVIC_SourceStatusClear(INT_SOURCE_SPI6_RX); // clear interrupt flag first because transfer complete callback may start new transfer
    if (readIndex < numberOfBytes) {
        return;
    }

    // End transfer
    if (csPin != GPIO_PIN_NONE) {
#ifdef SPI6_CS_ACTIVE_HIGH
        GPIO_PinClear(csPin);
#else
        GPIO_PinSet(csPin);
#endif
    }
#ifdef PRINT_TRANSFERS
    SpiPrintTransferComplete(data, numberOfBytes);
#endif
    if (transferComplete != NULL) {
        transferComplete();
    }
}

/**
 * @brief Returns true while the transfer is in progress.
 * @return True while the transfer is in progress.
 */
bool Spi6TransferInProgress(void) {
    return readIndex < numberOfBytes;
}

//------------------------------------------------------------------------------
// End of file
