import os

with open("HexToBitPattern.h", "w") as header_file:
    header_file.write("// This file was generated by " + os.path.basename(__file__) + "\n\n")
    header_file.write("#include <stdint.h>\n\n")
    header_file.write("static const uint32_t hexToBitPattern" + "[] = {")

    array_elements = ""

    for value in range(256):
        bits = "{0:08b}".format(value)

        reordered_bits = bits[6] + bits[7] + bits[4] + bits[5] + bits[2] + bits[3] + bits[0] + bits[1]

        array_elements += "0x" + reordered_bits.replace("0", "8").replace("1", "E") + ", "

    array_elements = array_elements[:-2]  # remove trailing comma and space

    header_file.write(array_elements)
    header_file.write("};\n")
